### ISSUE TITLE
CTP file formatting

### ISSUE THREAD

**Issue by Vader699** [Unibeautify/unibeautify#224] opened 2019-03-16 11:43 UTC
Using unibeautify with vscode on a ctp file.  It replaces the file contents with stats, i.e. if there were any errors found and how long it took to run.  

**Expected behavior**
Either disable formatting for just ctp files or how to set it up to format the html and php correctly.  I'm not sure if I have my config correctly but could not find good example.  

`unibeautifyrc.json`:

```json
{
  "CSS": {
    "beautifiers": ["Prettier", "Pretty Diff", "JS-Beautify"],
    "quotes": "double",
    "align_assignments": true,
    "end_with_semicolon": true,
    "multiline_ternary": "always",
    "pragma_insert": false,
    "newline_between_rules": true,
    "selector_separator_newline": true
  },
  "GraphQL": {
    "beautifiers": ["Prettier"],
    "quotes": "double",
    "end_with_semicolon": true,
    "pragma_insert": false,
    "jsx_brackets": true,
    "object_curly_spacing": true
  },
  "HTML": {
    "beautifiers": ["Pretty Diff", "JS-Beautify"],
    "quotes": "double",
    "wrap_line_length": 120,
    "align_assignments": true,
    "max_preserve_newlines": 1,
    "multiline_ternary": "always",
    "brace_style": "collapse",
    "indent_inner_html": true,
    "indent_scripts": "normal",
    "wrap_attributes": "force-aligned"
  },
  "JSON": {
    "beautifiers": ["Prettier", "Pretty Diff", "JS-Beautify"],
    "quotes": "double",
    "wrap_line_length": 120,
    "align_assignments": true,
    "end_with_semicolon": true,
    "max_preserve_newlines": 1,
    "multiline_ternary": "always",
    "pragma_insert": false,
    "end_with_newline": true,
    "arrow_parens": "as-needed",
    "brace_style": "collapse",
    "jsx_brackets": true,
    "object_curly_spacing": true,
    "comma_first": false,
    "keep_array_indentation": false,
    "newline_between_rules": true,
    "space_before_conditional": true,
    "space_in_empty_paren": false,
    "space_in_paren": true,
    "unescape_strings": true
  },
  "PHP": {
    "beautifiers": ["PHP_CodeSniffer"],
    "PHP_CodeSniffer": {
      "PHPCBF": {
        "path": "C:\\Users\\bab\\AppData\\Roaming\\Composer\\vendor\\bin\\phpcbf.bat"
      }
    }
  },
  "Less": {
    "beautifiers": ["Prettier", "Pretty Diff"],
    "indent_size": 2,
    "indent_style": "space",
    "quotes": "double",
    "wrap_line_length": 120,
    "align_assignments": true,
    "break_chained_methods": true,
    "end_with_semicolon": true,
    "indent_comments": true,
    "max_preserve_newlines": 1,
    "multiline_ternary": "always",
    "pragma_insert": false,
    "space_after_anon_function": false,
    "newline_between_rules": true
  }
}
```

**Comment by Glavin001** [comment] 2019-03-16 19:33
> Using unibeautify with vscode on a ctp file. It replaces the file contents with stats, i.e. if there were any errors found and how long it took to run.

Please provide an example file and screenshot of your VSCode window, so we can see the selected grammar for the file.

**Comment by Vader699** [comment] 2019-03-17 05:56
It's a mix of html and php and sometimes javascript.  It's a the file type cakephp uses for the views.  

Before
![Before](https://user-images.githubusercontent.com/1227567/54485929-34628980-484f-11e9-9785-55a5a89daf8d.jpg)

After
![After](https://user-images.githubusercontent.com/1227567/54485931-39bfd400-484f-11e9-8025-14e1c1bdc5f3.jpg)

**Comment by Glavin001** [comment] 2019-03-17 14:31
I cannot copy and paste from an image to make a failing test. Please copy your text and paste into a new Gist ( https://gist.github.com/ ) then share the link here. Thanks.

**Comment by Vader699** [comment] 2019-03-18 05:45
https://gist.github.com/Vader699/c86e537284e01d02004e4890cf400ee3#file-print_mail_log-ctp

Sorry misunderstood what you wanted.

**Comment by Glavin001** [comment] 2019-03-31 22:05
Looks like a duplicate of https://github.com/Unibeautify/beautifier-php-codesniffer/issues/5

@Vader699 please subscribe to the issue and comment there with any details you think may help. Pull Requests are welcome!

**Closed by Glavin001** 2019-03-31 22:05 UTC
Labels: question

**Comment by Vader699** [comment] 2019-04-03 07:27
Yes that seems like the same issue.  I switched over to using php-cs-fixer and it does not override the file now and fixes the php in the file.  

It would be nice if the html, js, and php all got formatted but it looks like that is being worked on in #29.  

Thank you for looking into this issue.
